services:
  db:
    image: postgres:16
    container_name: fm_postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - FreelanceMarket/.env
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fm_django
    restart: unless-stopped
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind :8000 --workers 3 --timeout 120 freelance_market.wsgi:application"
    volumes:
      - ./FreelanceMarket/profiles/migrations:/src/profiles/migrations
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8000:8000"
    env_file:
      - FreelanceMarket/.env
    depends_on:
      db:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
