# Generated by Django 5.0.4 on 2024-04-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nickname',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='executor',
            name='nickname',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
